# Generated by Django 4.0.3 on 2022-03-25 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfume',
            old_name='date_added',
            new_name='added_date',
        ),
        migrations.AddField(
            model_name='perfume',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
