# Generated by Django 4.0.3 on 2022-04-04 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_preference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preference',
        ),
    ]
