# Generated by Django 4.0.3 on 2022-04-12 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('predictor', '0004_delete_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('love', models.BooleanField()),
                ('comment', models.CharField(max_length=200)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictor.perfume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
