# Generated by Django 4.0.3 on 2022-04-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0005_preference'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='perfume',
            constraint=models.UniqueConstraint(fields=('name', 'house'), name='house_perfume_unique'),
        ),
    ]
