# Generated by Django 4.0.3 on 2022-04-13 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0006_perfume_house_perfume_unique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preference',
            old_name='modified_date',
            new_name='review_date',
        ),
    ]
