# Generated by Django 4.0.3 on 2022-04-17 18:28

from django.db import migrations, models


def back_fill_house(apps, schema_editor):
    Perfume = apps.get_model('predictor', 'Perfume')
    House = apps.get_model('predictor', 'House')

    for perfume in Perfume.objects.filter():
        if House.objects.filter(name=perfume.house) is None:
            house_link = House.objects.create(perfume.house)
            house_link.save()
            perfume.house_link = house_link
            perfume.save()


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0009_auto_20220417_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RunPython(back_fill_house, reverse_code=migrations.RunPython.noop,),
    ]
