# Generated by Django 4.0.3 on 2022-04-17 18:30

from django.db import migrations


def back_fill_house(apps, schema_editor):
    Perfume = apps.get_model('predictor', 'Perfume')
    House = apps.get_model('predictor', 'House')

    for perfume in Perfume.objects.filter():
        if House.objects.filter(name=perfume.house) is None:
            house_link = House.objects.create(perfume.house)
            house_link.save()
            perfume.house_link = house_link
            perfume.save()


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0010_alter_house_name'),
    ]

    operations = [
        migrations.RunPython(back_fill_house, reverse_code=migrations.RunPython.noop,),
    ]
