# Generated by Django 4.0.3 on 2022-04-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0012_alter_preference_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='review_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
