# Generated by Django 4.0.3 on 2022-04-12 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_preference_modified_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preference',
        ),
    ]
